import type { NextPage } from "next";
import Head from "next/head";
import HomeComp from "../components/HomeComp";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const Home: NextPage = () => {
  return (
    <div className={""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer />

      <main>
        <HomeComp />
      </main>

      <footer className={""}></footer>
    </div>
  );
};

export default Home;
